# Generated by Django 2.0.2 on 2018-05-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='histories',
            options={'verbose_name': 'Histories', 'verbose_name_plural': 'Histories'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Services', 'verbose_name_plural': 'Services'},
        ),
    ]
